//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareThings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int maxUsers { get; set; }
        public int maxTransactions { get; set; }
        public bool isPublic { get; set; }
        public string locationCode { get; set; }
        public bool isEnabled { get; set; }
    }
}
