//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareThings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public int reputation { get; set; }
        public int location_id { get; set; }
        public bool isFlagged { get; set; }
        public bool isDisabled { get; set; }
        public bool isAdmin { get; set; }
        public bool isDeleted { get; set; }
    }
}
